spring:
  application:
    name: mephi-bigdata
  main:
    web-application-type: none

metrics:
  enabled: true
  collection-interval-ms: 5000
  enabled-metrics:
    cpu: true
    ram: true
    disk: true
    network: true

nats:
  url: ${NATS_URL:nats://localhost:4222}
  stream:
    name: METRICS
    subjects:
      - metrics.system.*
  subject: metrics.system.snapshot  